### PR TITLE
Restrict focusables to keyboard focusable elements

### PR DESCRIPTION
**Pull request by scttdavs**
We have a use case where we have some focusable elements that are hidden in our dialog in one state, and shown in another state. However, makeup-keyboard-trap gets a hidden one and sets it as the `lastFocusableElement`. There does not appear to be a way around this without removing the hidden element from the DOM completely.

However, since it uses makeup-focusables, there is a supported feature to return only keyboard-focusable elements (ones with `tabindex !== '-1'`). That makes sense since this is a 'keyboard' trapping libarary, and also this way we can appropriately set tabindex on those hidden elements rather than remove/add them to the DOM repeatedly.

### CODE REVIEW

**Comment by ianmcburnie** [comment]
Oops, just saw this. Looking now...

**Review by ianmcburnie — APPROVED** [review]
Good catch. I will probably publish as a new minor version rather than as a patch (to be on the safe side). But this seems like the right behaviour going forward. Cheers!

**Comment by ianmcburnie** [comment]
The commit history is kinda weird, but I will squash :-)

**Comment by scttdavs** [comment]
thx!

**Pull request merged**
